### ISSUE TITLE
Request for Accessible Annotations

### ISSUE THREAD

**Issue by ashun989** [lorebianchi98/FG-OVD#1]
Hello, this is a great study! 
I would like to get the captions you built, but I noticed that the Llama30B model is too large, it consumes too many resources to generate using the code, and the most obtained annotations will be slightly different from the annotations you used due to the randomness of the Llama generation process. 
I would appreciate it if you could share the annotations in some way.

**Comment by lorebianchi98** [comment]
Hi! Thank you for showing interest in our study!

You can find the annotations utilized in the paper within the `benchmarks` folder of this repository. Additionally, we've recently made available the training and validation sets, which were generated using the same procedure applied to the benchmarks. These sets are located in the `training_sets` and `validation_sets` folders respectively. Feel free to reach out if you need any help!
