### ISSUE TITLE
Questions about the vild_reference.py file

### ISSUE THREAD

**Issue by chaishare** [lorebianchi98/FG-OVD#10]
I haven't seen this model file in this directory regarding saved_madel_dir here. Where should I download this file?
![save_model](https://github.com/user-attachments/assets/c2b90063-8874-4e16-811d-5ea3cba7d11a)

**Comment by lorebianchi98** [comment]
To run inference, you'll need to install the corresponding models by following the instructions from their respective repositories. For example, for ViLD, you can install the model from the official [ViLD repository](https://github.com/tensorflow/tpu/tree/master/models/official/detection/projects/vild). Our inference code on the benchmark is adapted from the [ViLD demo notebook](https://colab.research.google.com/github/tensorflow/tpu/blob/master/models/official/detection/projects/vild/ViLD_demo.ipynb#scrollTo=EM0y1Ym4JanX), which is provided by the authors.

**Comment by chaishare** [comment]
> To run inference, you'll need to install the corresponding models by following the instructions from their respective repositories. For example, for ViLD, you can install the model from the official [ViLD repository](https://github.com/tensorflow/tpu/tree/master/models/official/detection/projects/vild). Our inference code on the benchmark is adapted from the [ViLD demo notebook](https://colab.research.google.com/github/tensorflow/tpu/blob/master/models/official/detection/projects/vild/ViLD_demo.ipynb#scrollTo=EM0y1Ym4JanX), which is provided by the authors.

Got it, thank you for your response!
