### ISSUE TITLE
No dockerfile found

### ISSUE THREAD

**Issue by tengerye** [lorebianchi98/FG-OVD#4]
In the readme, the instruction is given as:
```
git clone https://github.com/lorebianchi98/FG-OVD.git
cd FG-OVD/docker
docker image build -t IMAGE_NAME - < Dockerfile
```

However, there is neither docker folder not dockerfile in this repository.

**Comment by lorebianchi98** [comment]
Thank you for pointing that out! There is indeed an error in the cd command. The correct path to the Dockerfile is actually inside `FG-OVD/captions_generations/docker`. I will fix this mistake right away.
