### ISSUE TITLE
About Detic model

### ISSUE THREAD

**Issue by iMayuqi** [lorebianchi98/FG-OVD#5]
Hello, author. 
I have some questions about the test results of the Detic model. The experimental result of the transparent subset we tested is much lower than that in the paper (24.8 in our test, 28 in the paper), while the other results are similar. I am worried that the reviewers will have questions about our data, could you please give me an explanation?

**Comment by lorebianchi98** [comment]
Thanks for reaching out and letting me know about this. Sorry for the delay in getting back to you.

I re-ran the evaluations, and you're right—the results match yours. We probably mistakenly introduced some inaccuracy while assembling the table within the paper.
Sorry for this oversight and thanks for catching this! I'll point out this correction in the README

**Comment by iMayuqi** [comment]
Thank you very much for your reply, which is very helpful to me. Good luck with your work！

**Comment by ysysys666** [comment]
Hi, I'm also testing Detic now, and I'm having some problems. When I run detic_inference.py, total_scores = outputs['instances'].total_scores says' AttributeError: Cannot find field 'total_scores' in the given Instances! Have you ever encountered a similar error, and I would appreciate your reply. @iMayuqi

**Comment by lorebianchi98** [comment]
Hi @ysysys666, I had to make some modifications to Detectron2 to enable Detic to return total_scores (i.e., the scores for every class in the vocabulary for each box).

You can find the customized version of Detectron2 to install at [this link](https://github.com/lorebianchi98/detectron2.git).

I'll update the README to clarify this part of the procedure :)
