### ISSUE TITLE
Could you release all the project code including training and inference stage.

### ISSUE THREAD

**Issue by yangt1013** [lorebianchi98/FG-OVD#7]
Thanks a lot for your code. 
could you release all the project contents, including training models, training files, Table 2 and Table 3 model's files. there are only generate dataset instruction.

**Comment by lorebianchi98** [comment]
Thank you for your interest in our work!

To clarify, while we've shared the training and validation datasets, **we did not train any models** as part of this project. All the methods evaluated in our work are based on **pre-trained models**. For further details, including checkpoints and installation instructions, please refer to the official repositories of those models.

You can find the scripts used to generate predictions on the FG-OVD benchmark suite [here](https://github.com/lorebianchi98/FG-OVD/tree/main/detectors_inferences), which will allow you to evaluate the pre-trained models against our benchmarks. Afterward, use [this script](https://github.com/lorebianchi98/FG-OVD/blob/main/evaluation/evaluate_map.py) to calculate the mAP values presented in **Table 2** and **Table 3**.

I hope this clears up any confusion, and feel free to reach out if you have any more questions!

**Comment by yangt1013** [comment]
Thanks for your reply. About some another problems. 
Could you provide the details how to generate dataset step by step.
I met some problems with following link https://huggingface.co/OpenAssistant/oasst-sft-6-llama-30b-xor/blob/main/README.md
Did you download the LLM weights directly to the captions_generation/models or install by the link instructions.

**Comment by lorebianchi98** [comment]
The first step is to obtain the Llama 2 model weights. You'll first need to request them [here](https://www.llama.com/llama-downloads). Once approved, follow the instructions provided in the [README of the link you shared](https://huggingface.co/OpenAssistant/oasst-sft-6-llama-30b-xor/blob/main/README.md). After setting everything up, place the downloaded model weights into the _**captions_generation/models**_ directory.
